In [106]:
import math
import numpy as np
import pandas  as pd 
import matplotlib as plot 

In [107]:
def del_spec(a,b,N,k,n):
    ds = np.zeros(n)
    for i in range(0,n):
        ds[i] = N-b*(math.floor(i/a))-(i%a)
#         print(ds[i])
        N = ds[0]-ds[n-1]
    return ds

In [109]:
# Program for finding test cases satisfying the constraints
cnt = 0
CNT = 0
for T in range(4,40):
    for a1 in range(1,T):
        for a2 in range(1,T):
            for b1 in range(a1+1,T):
                 for b2 in range(a2+1,T):
                        if(a1==a2 and b1!=b2):
                            flag_dc = 0
                            flag_dsc = 0
                            if(T - b2 > b1 and T - b1 > b2):
                                k = max(a1,a2)*min((T-b2-a1+1)/b1,(T-b1-a2+1)/b2)
                                if(k.is_integer()):
                                    k = int(k)
                                    CNT +=1
                                    ds1=del_spec(a1,b1,T-b2,k,k+a1)
                                    ds2=del_spec(a2,b2,T-b1,k,k+a2)

#----------------------------------Delay Constraint----------------------------------------------------- 
                                    for i in range(0,k):
                                        if (ds1[i]+ ds2[k-i-1])>T:
#                                         if (ds1[a1-1]+ ds2[k-a1])>T:
                                            flag_dc = 1
# ------------------------------------------------------------------------------------------------------                                    
                                    if(flag_dc ==0 and ds2[k+a2-1]>=0 and ds1[k+a1-1]>=0):
                                        cnt +=1
                                        print(k,T,a1,b1,a2,b2)
                                        print(ds1)
                                        print(ds2)

2 8 2 3 2 4
[4. 3. 1. 0.]
[5. 4. 1. 0.]
2 8 2 4 2 3
[5. 4. 1. 0.]
[4. 3. 1. 0.]
2 9 2 3 2 5
[4. 3. 1. 0.]
[6. 5. 1. 0.]
2 9 2 5 2 3
[6. 5. 1. 0.]
[4. 3. 1. 0.]
2 10 2 3 2 6
[4. 3. 1. 0.]
[7. 6. 1. 0.]
2 10 2 4 2 5
[5. 4. 1. 0.]
[6. 5. 1. 0.]
2 10 2 5 2 4
[6. 5. 1. 0.]
[5. 4. 1. 0.]
2 10 2 6 2 3
[7. 6. 1. 0.]
[4. 3. 1. 0.]
2 11 2 3 2 7
[4. 3. 1. 0.]
[8. 7. 1. 0.]
2 11 2 4 2 6
[5. 4. 1. 0.]
[7. 6. 1. 0.]
2 11 2 6 2 4
[7. 6. 1. 0.]
[5. 4. 1. 0.]
2 11 2 7 2 3
[8. 7. 1. 0.]
[4. 3. 1. 0.]
3 11 3 4 3 5
[6. 5. 4. 2. 1. 0.]
[7. 6. 5. 2. 1. 0.]
3 11 3 5 3 4
[7. 6. 5. 2. 1. 0.]
[6. 5. 4. 2. 1. 0.]
2 12 2 3 2 8
[4. 3. 1. 0.]
[9. 8. 1. 0.]
2 12 2 4 2 7
[5. 4. 1. 0.]
[8. 7. 1. 0.]
2 12 2 5 2 6
[6. 5. 1. 0.]
[7. 6. 1. 0.]
2 12 2 6 2 5
[7. 6. 1. 0.]
[6. 5. 1. 0.]
2 12 2 7 2 4
[8. 7. 1. 0.]
[5. 4. 1. 0.]
2 12 2 8 2 3
[9. 8. 1. 0.]
[4. 3. 1. 0.]
3 12 3 4 3 6
[6. 5. 4. 2. 1. 0.]
[8. 7. 6. 2. 1. 0.]
3 12 3 6 3 4
[8. 7. 6. 2. 1. 0.]
[6. 5. 4. 2. 1. 0.]
2 13 2 3 2 9
[4. 3. 1. 0.]
[10.  9.  1.  0.]
2 13 2 4 

[9. 8. 7. 2. 1. 0.]
3 21 3 13 3 6
[15. 14. 13.  2.  1.  0.]
[8. 7. 6. 2. 1. 0.]
3 21 3 14 3 5
[16. 15. 14.  2.  1.  0.]
[7. 6. 5. 2. 1. 0.]
3 21 3 15 3 4
[17. 16. 15.  2.  1.  0.]
[6. 5. 4. 2. 1. 0.]
4 21 4 5 4 13
[8. 7. 6. 5. 3. 2. 1. 0.]
[16. 15. 14. 13.  3.  2.  1.  0.]
4 21 4 6 4 12
[9. 8. 7. 6. 3. 2. 1. 0.]
[15. 14. 13. 12.  3.  2.  1.  0.]
4 21 4 7 4 11
[10.  9.  8.  7.  3.  2.  1.  0.]
[14. 13. 12. 11.  3.  2.  1.  0.]
4 21 4 8 4 10
[11. 10.  9.  8.  3.  2.  1.  0.]
[13. 12. 11. 10.  3.  2.  1.  0.]
4 21 4 10 4 8
[13. 12. 11. 10.  3.  2.  1.  0.]
[11. 10.  9.  8.  3.  2.  1.  0.]
4 21 4 11 4 7
[14. 13. 12. 11.  3.  2.  1.  0.]
[10.  9.  8.  7.  3.  2.  1.  0.]
4 21 4 12 4 6
[15. 14. 13. 12.  3.  2.  1.  0.]
[9. 8. 7. 6. 3. 2. 1. 0.]
4 21 4 13 4 5
[16. 15. 14. 13.  3.  2.  1.  0.]
[8. 7. 6. 5. 3. 2. 1. 0.]
5 21 5 6 5 11
[10.  9.  8.  7.  6.  4.  3.  2.  1.  0.]
[15. 14. 13. 12. 11.  4.  3.  2.  1.  0.]
5 21 5 7 5 10
[11. 10.  9.  8.  7.  4.  3.  2.  1.  0.]
[14. 13. 12. 11. 10.  

5 25 5 6 5 15
[10.  9.  8.  7.  6.  4.  3.  2.  1.  0.]
[19. 18. 17. 16. 15.  4.  3.  2.  1.  0.]
5 25 5 7 5 14
[11. 10.  9.  8.  7.  4.  3.  2.  1.  0.]
[18. 17. 16. 15. 14.  4.  3.  2.  1.  0.]
5 25 5 8 5 13
[12. 11. 10.  9.  8.  4.  3.  2.  1.  0.]
[17. 16. 15. 14. 13.  4.  3.  2.  1.  0.]
5 25 5 9 5 12
[13. 12. 11. 10.  9.  4.  3.  2.  1.  0.]
[16. 15. 14. 13. 12.  4.  3.  2.  1.  0.]
5 25 5 10 5 11
[14. 13. 12. 11. 10.  4.  3.  2.  1.  0.]
[15. 14. 13. 12. 11.  4.  3.  2.  1.  0.]
5 25 5 11 5 10
[15. 14. 13. 12. 11.  4.  3.  2.  1.  0.]
[14. 13. 12. 11. 10.  4.  3.  2.  1.  0.]
5 25 5 12 5 9
[16. 15. 14. 13. 12.  4.  3.  2.  1.  0.]
[13. 12. 11. 10.  9.  4.  3.  2.  1.  0.]
5 25 5 13 5 8
[17. 16. 15. 14. 13.  4.  3.  2.  1.  0.]
[12. 11. 10.  9.  8.  4.  3.  2.  1.  0.]
5 25 5 14 5 7
[18. 17. 16. 15. 14.  4.  3.  2.  1.  0.]
[11. 10.  9.  8.  7.  4.  3.  2.  1.  0.]
5 25 5 15 5 6
[19. 18. 17. 16. 15.  4.  3.  2.  1.  0.]
[10.  9.  8.  7.  6.  4.  3.  2.  1.  0.]
6 25 6 7 6 13
[12.

[12. 11. 10.  2.  1.  0.]
3 28 3 17 3 9
[19. 18. 17.  2.  1.  0.]
[11. 10.  9.  2.  1.  0.]
3 28 3 18 3 8
[20. 19. 18.  2.  1.  0.]
[10.  9.  8.  2.  1.  0.]
3 28 3 19 3 7
[21. 20. 19.  2.  1.  0.]
[9. 8. 7. 2. 1. 0.]
3 28 3 20 3 6
[22. 21. 20.  2.  1.  0.]
[8. 7. 6. 2. 1. 0.]
3 28 3 21 3 5
[23. 22. 21.  2.  1.  0.]
[7. 6. 5. 2. 1. 0.]
3 28 3 22 3 4
[24. 23. 22.  2.  1.  0.]
[6. 5. 4. 2. 1. 0.]
4 28 4 5 4 20
[8. 7. 6. 5. 3. 2. 1. 0.]
[23. 22. 21. 20.  3.  2.  1.  0.]
4 28 4 6 4 19
[9. 8. 7. 6. 3. 2. 1. 0.]
[22. 21. 20. 19.  3.  2.  1.  0.]
4 28 4 7 4 18
[10.  9.  8.  7.  3.  2.  1.  0.]
[21. 20. 19. 18.  3.  2.  1.  0.]
4 28 4 8 4 17
[11. 10.  9.  8.  3.  2.  1.  0.]
[20. 19. 18. 17.  3.  2.  1.  0.]
4 28 4 9 4 16
[12. 11. 10.  9.  3.  2.  1.  0.]
[19. 18. 17. 16.  3.  2.  1.  0.]
4 28 4 10 4 15
[13. 12. 11. 10.  3.  2.  1.  0.]
[18. 17. 16. 15.  3.  2.  1.  0.]
4 28 4 11 4 14
[14. 13. 12. 11.  3.  2.  1.  0.]
[17. 16. 15. 14.  3.  2.  1.  0.]
4 28 4 12 4 13
[15. 14. 13. 12.  3.  2.  1

[25. 24. 23. 22.  3.  2.  1.  0.]
[8. 7. 6. 5. 3. 2. 1. 0.]
5 30 5 6 5 20
[10.  9.  8.  7.  6.  4.  3.  2.  1.  0.]
[24. 23. 22. 21. 20.  4.  3.  2.  1.  0.]
5 30 5 7 5 19
[11. 10.  9.  8.  7.  4.  3.  2.  1.  0.]
[23. 22. 21. 20. 19.  4.  3.  2.  1.  0.]
5 30 5 8 5 18
[12. 11. 10.  9.  8.  4.  3.  2.  1.  0.]
[22. 21. 20. 19. 18.  4.  3.  2.  1.  0.]
5 30 5 9 5 17
[13. 12. 11. 10.  9.  4.  3.  2.  1.  0.]
[21. 20. 19. 18. 17.  4.  3.  2.  1.  0.]
5 30 5 10 5 16
[14. 13. 12. 11. 10.  4.  3.  2.  1.  0.]
[20. 19. 18. 17. 16.  4.  3.  2.  1.  0.]
5 30 5 11 5 15
[15. 14. 13. 12. 11.  4.  3.  2.  1.  0.]
[19. 18. 17. 16. 15.  4.  3.  2.  1.  0.]
5 30 5 12 5 14
[16. 15. 14. 13. 12.  4.  3.  2.  1.  0.]
[18. 17. 16. 15. 14.  4.  3.  2.  1.  0.]
5 30 5 14 5 12
[18. 17. 16. 15. 14.  4.  3.  2.  1.  0.]
[16. 15. 14. 13. 12.  4.  3.  2.  1.  0.]
5 30 5 15 5 11
[19. 18. 17. 16. 15.  4.  3.  2.  1.  0.]
[15. 14. 13. 12. 11.  4.  3.  2.  1.  0.]
5 30 5 16 5 10
[20. 19. 18. 17. 16.  4.  3.  2.  1.  

[24. 23. 22. 21.  3.  2.  1.  0.]
[11. 10.  9.  8.  3.  2.  1.  0.]
4 32 4 22 4 7
[25. 24. 23. 22.  3.  2.  1.  0.]
[10.  9.  8.  7.  3.  2.  1.  0.]
4 32 4 23 4 6
[26. 25. 24. 23.  3.  2.  1.  0.]
[9. 8. 7. 6. 3. 2. 1. 0.]
4 32 4 24 4 5
[27. 26. 25. 24.  3.  2.  1.  0.]
[8. 7. 6. 5. 3. 2. 1. 0.]
5 32 5 6 5 22
[10.  9.  8.  7.  6.  4.  3.  2.  1.  0.]
[26. 25. 24. 23. 22.  4.  3.  2.  1.  0.]
5 32 5 7 5 21
[11. 10.  9.  8.  7.  4.  3.  2.  1.  0.]
[25. 24. 23. 22. 21.  4.  3.  2.  1.  0.]
5 32 5 8 5 20
[12. 11. 10.  9.  8.  4.  3.  2.  1.  0.]
[24. 23. 22. 21. 20.  4.  3.  2.  1.  0.]
5 32 5 9 5 19
[13. 12. 11. 10.  9.  4.  3.  2.  1.  0.]
[23. 22. 21. 20. 19.  4.  3.  2.  1.  0.]
5 32 5 10 5 18
[14. 13. 12. 11. 10.  4.  3.  2.  1.  0.]
[22. 21. 20. 19. 18.  4.  3.  2.  1.  0.]
5 32 5 11 5 17
[15. 14. 13. 12. 11.  4.  3.  2.  1.  0.]
[21. 20. 19. 18. 17.  4.  3.  2.  1.  0.]
5 32 5 12 5 16
[16. 15. 14. 13. 12.  4.  3.  2.  1.  0.]
[20. 19. 18. 17. 16.  4.  3.  2.  1.  0.]
5 32 5 13 5 1

2 34 2 3 2 30
[4. 3. 1. 0.]
[31. 30.  1.  0.]
2 34 2 4 2 29
[5. 4. 1. 0.]
[30. 29.  1.  0.]
2 34 2 5 2 28
[6. 5. 1. 0.]
[29. 28.  1.  0.]
2 34 2 6 2 27
[7. 6. 1. 0.]
[28. 27.  1.  0.]
2 34 2 7 2 26
[8. 7. 1. 0.]
[27. 26.  1.  0.]
2 34 2 8 2 25
[9. 8. 1. 0.]
[26. 25.  1.  0.]
2 34 2 9 2 24
[10.  9.  1.  0.]
[25. 24.  1.  0.]
2 34 2 10 2 23
[11. 10.  1.  0.]
[24. 23.  1.  0.]
2 34 2 11 2 22
[12. 11.  1.  0.]
[23. 22.  1.  0.]
2 34 2 12 2 21
[13. 12.  1.  0.]
[22. 21.  1.  0.]
2 34 2 13 2 20
[14. 13.  1.  0.]
[21. 20.  1.  0.]
2 34 2 14 2 19
[15. 14.  1.  0.]
[20. 19.  1.  0.]
2 34 2 15 2 18
[16. 15.  1.  0.]
[19. 18.  1.  0.]
2 34 2 16 2 17
[17. 16.  1.  0.]
[18. 17.  1.  0.]
2 34 2 17 2 16
[18. 17.  1.  0.]
[17. 16.  1.  0.]
2 34 2 18 2 15
[19. 18.  1.  0.]
[16. 15.  1.  0.]
2 34 2 19 2 14
[20. 19.  1.  0.]
[15. 14.  1.  0.]
2 34 2 20 2 13
[21. 20.  1.  0.]
[14. 13.  1.  0.]
2 34 2 21 2 12
[22. 21.  1.  0.]
[13. 12.  1.  0.]
2 34 2 22 2 11
[23. 22.  1.  0.]
[12. 11.  1.  0.]
2 34 2 23 2

7 35 7 10 7 19
[16. 15. 14. 13. 12. 11. 10.  6.  5.  4.  3.  2.  1.  0.]
[25. 24. 23. 22. 21. 20. 19.  6.  5.  4.  3.  2.  1.  0.]
7 35 7 11 7 18
[17. 16. 15. 14. 13. 12. 11.  6.  5.  4.  3.  2.  1.  0.]
[24. 23. 22. 21. 20. 19. 18.  6.  5.  4.  3.  2.  1.  0.]
7 35 7 12 7 17
[18. 17. 16. 15. 14. 13. 12.  6.  5.  4.  3.  2.  1.  0.]
[23. 22. 21. 20. 19. 18. 17.  6.  5.  4.  3.  2.  1.  0.]
7 35 7 13 7 16
[19. 18. 17. 16. 15. 14. 13.  6.  5.  4.  3.  2.  1.  0.]
[22. 21. 20. 19. 18. 17. 16.  6.  5.  4.  3.  2.  1.  0.]
7 35 7 14 7 15
[20. 19. 18. 17. 16. 15. 14.  6.  5.  4.  3.  2.  1.  0.]
[21. 20. 19. 18. 17. 16. 15.  6.  5.  4.  3.  2.  1.  0.]
7 35 7 15 7 14
[21. 20. 19. 18. 17. 16. 15.  6.  5.  4.  3.  2.  1.  0.]
[20. 19. 18. 17. 16. 15. 14.  6.  5.  4.  3.  2.  1.  0.]
7 35 7 16 7 13
[22. 21. 20. 19. 18. 17. 16.  6.  5.  4.  3.  2.  1.  0.]
[19. 18. 17. 16. 15. 14. 13.  6.  5.  4.  3.  2.  1.  0.]
7 35 7 17 7 12
[23. 22. 21. 20. 19. 18. 17.  6.  5.  4.  3.  2.  1.  0.]
[18. 17. 1

3 37 3 4 3 31
[6. 5. 4. 2. 1. 0.]
[33. 32. 31.  2.  1.  0.]
3 37 3 5 3 30
[7. 6. 5. 2. 1. 0.]
[32. 31. 30.  2.  1.  0.]
3 37 3 6 3 29
[8. 7. 6. 2. 1. 0.]
[31. 30. 29.  2.  1.  0.]
3 37 3 7 3 28
[9. 8. 7. 2. 1. 0.]
[30. 29. 28.  2.  1.  0.]
3 37 3 8 3 27
[10.  9.  8.  2.  1.  0.]
[29. 28. 27.  2.  1.  0.]
3 37 3 9 3 26
[11. 10.  9.  2.  1.  0.]
[28. 27. 26.  2.  1.  0.]
3 37 3 10 3 25
[12. 11. 10.  2.  1.  0.]
[27. 26. 25.  2.  1.  0.]
3 37 3 11 3 24
[13. 12. 11.  2.  1.  0.]
[26. 25. 24.  2.  1.  0.]
3 37 3 12 3 23
[14. 13. 12.  2.  1.  0.]
[25. 24. 23.  2.  1.  0.]
3 37 3 13 3 22
[15. 14. 13.  2.  1.  0.]
[24. 23. 22.  2.  1.  0.]
3 37 3 14 3 21
[16. 15. 14.  2.  1.  0.]
[23. 22. 21.  2.  1.  0.]
3 37 3 15 3 20
[17. 16. 15.  2.  1.  0.]
[22. 21. 20.  2.  1.  0.]
3 37 3 16 3 19
[18. 17. 16.  2.  1.  0.]
[21. 20. 19.  2.  1.  0.]
3 37 3 17 3 18
[19. 18. 17.  2.  1.  0.]
[20. 19. 18.  2.  1.  0.]
3 37 3 18 3 17
[20. 19. 18.  2.  1.  0.]
[19. 18. 17.  2.  1.  0.]
3 37 3 19 3 16
[21. 20. 1

5 38 5 21 5 13
[25. 24. 23. 22. 21.  4.  3.  2.  1.  0.]
[17. 16. 15. 14. 13.  4.  3.  2.  1.  0.]
5 38 5 22 5 12
[26. 25. 24. 23. 22.  4.  3.  2.  1.  0.]
[16. 15. 14. 13. 12.  4.  3.  2.  1.  0.]
5 38 5 23 5 11
[27. 26. 25. 24. 23.  4.  3.  2.  1.  0.]
[15. 14. 13. 12. 11.  4.  3.  2.  1.  0.]
5 38 5 24 5 10
[28. 27. 26. 25. 24.  4.  3.  2.  1.  0.]
[14. 13. 12. 11. 10.  4.  3.  2.  1.  0.]
5 38 5 25 5 9
[29. 28. 27. 26. 25.  4.  3.  2.  1.  0.]
[13. 12. 11. 10.  9.  4.  3.  2.  1.  0.]
5 38 5 26 5 8
[30. 29. 28. 27. 26.  4.  3.  2.  1.  0.]
[12. 11. 10.  9.  8.  4.  3.  2.  1.  0.]
5 38 5 27 5 7
[31. 30. 29. 28. 27.  4.  3.  2.  1.  0.]
[11. 10.  9.  8.  7.  4.  3.  2.  1.  0.]
5 38 5 28 5 6
[32. 31. 30. 29. 28.  4.  3.  2.  1.  0.]
[10.  9.  8.  7.  6.  4.  3.  2.  1.  0.]
6 38 6 7 6 26
[12. 11. 10.  9.  8.  7.  5.  4.  3.  2.  1.  0.]
[31. 30. 29. 28. 27. 26.  5.  4.  3.  2.  1.  0.]
6 38 6 8 6 25
[13. 12. 11. 10.  9.  8.  5.  4.  3.  2.  1.  0.]
[30. 29. 28. 27. 26. 25.  5.  4.  

7 39 7 24 7 9
[30. 29. 28. 27. 26. 25. 24.  6.  5.  4.  3.  2.  1.  0.]
[15. 14. 13. 12. 11. 10.  9.  6.  5.  4.  3.  2.  1.  0.]
7 39 7 25 7 8
[31. 30. 29. 28. 27. 26. 25.  6.  5.  4.  3.  2.  1.  0.]
[14. 13. 12. 11. 10.  9.  8.  6.  5.  4.  3.  2.  1.  0.]
8 39 8 9 8 23
[16. 15. 14. 13. 12. 11. 10.  9.  7.  6.  5.  4.  3.  2.  1.  0.]
[30. 29. 28. 27. 26. 25. 24. 23.  7.  6.  5.  4.  3.  2.  1.  0.]
8 39 8 10 8 22
[17. 16. 15. 14. 13. 12. 11. 10.  7.  6.  5.  4.  3.  2.  1.  0.]
[29. 28. 27. 26. 25. 24. 23. 22.  7.  6.  5.  4.  3.  2.  1.  0.]
8 39 8 11 8 21
[18. 17. 16. 15. 14. 13. 12. 11.  7.  6.  5.  4.  3.  2.  1.  0.]
[28. 27. 26. 25. 24. 23. 22. 21.  7.  6.  5.  4.  3.  2.  1.  0.]
8 39 8 12 8 20
[19. 18. 17. 16. 15. 14. 13. 12.  7.  6.  5.  4.  3.  2.  1.  0.]
[27. 26. 25. 24. 23. 22. 21. 20.  7.  6.  5.  4.  3.  2.  1.  0.]
8 39 8 13 8 19
[20. 19. 18. 17. 16. 15. 14. 13.  7.  6.  5.  4.  3.  2.  1.  0.]
[26. 25. 24. 23. 22. 21. 20. 19.  7.  6.  5.  4.  3.  2.  1.  0.]
8 39 8

In [110]:
cnt

2274

In [111]:
CNT

4956

## Rate Calculator

In [90]:
data = []
for T in range(4,20):
    for a1 in range(1,T):
        for a2 in range(1,T):
            for b1 in range(a1+1,T):
                 for b2 in range(a2+1,T):
                    if(a1==a2 and b1!=b2 and T - b2 > b1 and T - b1 > b2):
                        R_opt = min((T-b2-a1+1)/(T-b2-a1+1+b1),(T-b1-a2+1)/(T-b1-a2+1+b2))
                        for k in range(1,T):
                            R=-1 
                            flag_dc = 0
                            flag_dsc = 0
                            ds1=del_spec(a1,b1,T-b2,k,k+a1)
                            ds2=del_spec(a2,b2,T-b1,k,k+a2)
                            for i in range(0,k):
                                if (ds1[i]+ ds2[k-i-1])>T:
                                    flag_dc = 1
                            if(ds2[k+a2-1]>=0 and ds1[k+a1-1]>=0):
                                flag_dsc = 1 
                            if(flag_dc == 0 and flag_dsc==1):
                                R = k/(k+max(a1,a2))
                            temp1 = math.floor((T-b2-1)/b1)*a1 + min(a1,(T-b2+1)%b1)-a1
                            temp2 = math.floor((T-b1-1)/b2)*a2 + min(a2,(T-b1+1)%b2)-a2
                            data.append((T,a1,a2,b1,b2,k,temp1,temp2,R,R_opt))

In [93]:
df = pd.DataFrame(data, columns = ['T', 'a1',"a2","b1","b2","k","temp1","temp2","R","R_opt"])

In [113]:
df

T  a1  a2  b1  b2   k  temp1  temp2    R     R_opt
0       6   1   1   2   3   1      0      1 -1.0  0.571429
1       6   1   1   2   3   2      0      1 -1.0  0.571429
2       6   1   1   2   3   3      0      1 -1.0  0.571429
3       6   1   1   2   3   4      0      1 -1.0  0.571429
4       6   1   1   2   3   5      0      1 -1.0  0.571429
...    ..  ..  ..  ..  ..  ..    ...    ...  ...       ...
23011  19   7   7  10   8  14      2      2 -1.0  0.272727
23012  19   7   7  10   8  15      2      2 -1.0  0.272727
23013  19   7   7  10   8  16      2      2 -1.0  0.272727
23014  19   7   7  10   8  17      2      2 -1.0  0.272727
23015  19   7   7  10   8  18      2      2 -1.0  0.272727

[23016 rows x 10 columns]

In [114]:
yf = df[df["R"]!=-1]
# yf[yf["R"]==yf["R_opt"]]
yf

T  a1  a2  b1  b2  k  temp1  temp2         R     R_opt
91      8   2   2   3   4  2      2      2  0.500000  0.500000
98      8   2   2   4   3  2      2      2  0.500000  0.500000
209     9   2   2   3   5  2      2      2  0.500000  0.500000
225     9   2   2   5   3  2      2      2  0.500000  0.500000
413    10   2   2   3   6  2      2      2  0.500000  0.500000
...    ..  ..  ..  ..  .. ..    ...    ...       ...       ...
22927  19   6   6  11   7  2      2      2  0.250000  0.300000
22946  19   7   7   8   9  3      3      3  0.300000  0.333333
22963  19   7   7   8  10  2      2      2  0.222222  0.272727
22982  19   7   7   9   8  3      3      3  0.300000  0.333333
22999  19   7   7  10   8  2      2      2  0.222222  0.272727

[384 rows x 10 columns]

In [112]:
pd. set_option("display.max_rows", 10) 
pd.set_option("display.max_rows", 10)